# Generated by Django 4.2.4 on 2023-08-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='custom_post_table_name',
        ),
    ]
